"""Brokerage API endpoints for Questrade integration.

Handles OAuth connection, account selection, trade sync, and
match confirmation/rejection.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from database.connection import get_db
from middleware.auth import CurrentUser
from services.questrade_service import QuestradeService
from services.trade_matcher import find_matches

router = APIRouter(prefix="/brokerage", tags=["brokerage"])

_qt_service = QuestradeService()


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class BrokerageConnectRequest(BaseModel):
    """Request body for connecting via manual refresh token (fallback)."""

    refresh_token: str
    is_practice: bool = False


class BrokerageOAuthRequest(BaseModel):
    """Request body for connecting via OAuth authorization code."""

    code: str
    redirect_uri: str
    is_practice: bool = False


class BrokerageConnectResponse(BaseModel):
    """Response after successfully connecting to Questrade."""

    connected: bool
    accounts: list[dict[str, Any]]


class BrokerageAuthorizeResponse(BaseModel):
    """Response containing the Questrade OAuth authorize URL."""

    url: str | None = None
    oauth_enabled: bool = False


class BrokerageStatusResponse(BaseModel):
    """Current Questrade connection status."""

    connected: bool
    account_id: str | None = None
    account_type: str | None = None
    is_practice: bool = False
    connected_at: str | None = None
    updated_at: str | None = None


class BrokerageSelectAccountRequest(BaseModel):
    """Request body for selecting a Questrade account."""

    account_id: str
    account_type: str


class BrokerageSyncRequest(BaseModel):
    """Request body for triggering a trade sync."""

    days_back: int = 30


class PendingMatchResponse(BaseModel):
    """A pending match between a Questrade execution and a recommendation."""

    id: str
    recommendation_id: str
    questrade_order_id: str
    ticker: str
    side: str
    avg_price: float
    total_shares: int
    total_commission: float
    currency: str
    executed_at: str
    match_score: float
    match_reason: str
    status: str
    rec_ticker: str = ""
    rec_action: str = ""
    rec_confidence: float = 0.0
    rec_entry_price: float | None = None


class ConfirmMatchRequest(BaseModel):
    """Request body for confirming a pending match."""

    match_id: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("/authorize-url", response_model=BrokerageAuthorizeResponse)
async def get_authorize_url(
    redirect_uri: str,
    is_practice: bool = False,
    state: str = "",
) -> BrokerageAuthorizeResponse:
    """Build the Questrade OAuth authorize URL for redirect-based sign-in.

    No auth required — the URL is harmless without an exchange step.
    The ``state`` param should be a CSRF token generated by the frontend.
    """
    url = QuestradeService.get_authorize_url(redirect_uri, is_practice=is_practice, state=state)
    return BrokerageAuthorizeResponse(url=url, oauth_enabled=url is not None)


@router.post("/connect-oauth", response_model=BrokerageConnectResponse)
async def connect_brokerage_oauth(
    body: BrokerageOAuthRequest,
    user_id: CurrentUser,
) -> BrokerageConnectResponse:
    """Exchange an OAuth authorization code for tokens and establish a connection."""
    try:
        result = await _qt_service.connect_with_code(
            user_id,
            body.code,
            body.redirect_uri,
            is_practice=body.is_practice,
        )
        return BrokerageConnectResponse(
            connected=result["connected"],
            accounts=result["accounts"],
        )
    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail=f"Questrade OAuth failed: {exc}",
        ) from exc


@router.post("/connect", response_model=BrokerageConnectResponse)
async def connect_brokerage(
    body: BrokerageConnectRequest,
    user_id: CurrentUser,
) -> BrokerageConnectResponse:
    """Exchange a manual Questrade refresh token (dev/fallback)."""
    try:
        result = await _qt_service.connect(
            user_id, body.refresh_token, is_practice=body.is_practice
        )
        return BrokerageConnectResponse(
            connected=result["connected"],
            accounts=result["accounts"],
        )
    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail=f"Failed to connect to Questrade: {exc}",
        ) from exc


@router.delete("/disconnect")
async def disconnect_brokerage(user_id: CurrentUser) -> dict[str, bool]:
    """Remove the stored Questrade connection."""
    await _qt_service.disconnect(user_id)
    return {"disconnected": True}


@router.get("/status", response_model=BrokerageStatusResponse)
async def brokerage_status(user_id: CurrentUser) -> BrokerageStatusResponse:
    """Return the current Questrade connection status."""
    status = await _qt_service.get_status(user_id)
    if not status:
        return BrokerageStatusResponse(connected=False)
    return BrokerageStatusResponse(
        connected=True,
        account_id=status.get("account_id"),
        account_type=status.get("account_type"),
        is_practice=status.get("is_practice", False),
        connected_at=str(status["connected_at"]) if status.get("connected_at") else None,
        updated_at=str(status["updated_at"]) if status.get("updated_at") else None,
    )


@router.get("/accounts")
async def list_accounts(user_id: CurrentUser) -> list[dict[str, Any]]:
    """Fetch the list of Questrade accounts for the connected user."""
    try:
        return await _qt_service.get_accounts(user_id)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@router.post("/select-account")
async def select_account(
    body: BrokerageSelectAccountRequest,
    user_id: CurrentUser,
) -> dict[str, bool]:
    """Save the user's selected Questrade account."""
    await _qt_service.select_account(user_id, body.account_id, body.account_type)
    return {"selected": True}


@router.post("/sync", response_model=list[PendingMatchResponse])
async def sync_trades(
    body: BrokerageSyncRequest,
    user_id: CurrentUser,
) -> list[PendingMatchResponse]:
    """Sync recent Questrade executions and match against recommendations."""
    now = datetime.now(tz=UTC)
    start = now - timedelta(days=body.days_back)
    start_str = start.isoformat()
    end_str = now.isoformat()

    try:
        executions = await _qt_service.get_executions(user_id, start_str, end_str)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    matches = await find_matches(user_id, executions, _qt_service)
    return [_match_to_response(m) for m in matches]


@router.get("/pending-matches", response_model=list[PendingMatchResponse])
async def list_pending_matches(user_id: CurrentUser) -> list[PendingMatchResponse]:
    """List pending trade matches for the current user."""
    client = await get_db()
    resp = (
        await client.table("pending_matches")
        .select("*")
        .eq("user_id", user_id)
        .eq("status", "pending")
        .order("created_at", desc=True)
        .execute()
    )

    matches = resp.data or []
    enriched = await _enrich_matches_with_recs(matches)
    return [_match_to_response(m) for m in enriched]


@router.post("/confirm-match")
async def confirm_match(
    body: ConfirmMatchRequest,
    user_id: CurrentUser,
) -> dict[str, str]:
    """Confirm a pending match and create an outcome from the brokerage data."""
    client = await get_db()

    match_resp = (
        await client.table("pending_matches")
        .select("*")
        .eq("id", body.match_id)
        .eq("user_id", user_id)
        .eq("status", "pending")
        .maybe_single()
        .execute()
    )
    if not match_resp or not match_resp.data:
        raise HTTPException(status_code=404, detail="Pending match not found")

    match = match_resp.data
    rec_id = match["recommendation_id"]

    dec_resp = (
        await client.table("decisions")
        .select("id")
        .eq("recommendation_id", rec_id)
        .eq("user_id", user_id)
        .eq("decision", "following")
        .maybe_single()
        .execute()
    )
    if not dec_resp or not dec_resp.data:
        raise HTTPException(
            status_code=400,
            detail="No 'following' decision found for this recommendation",
        )

    decision_id = dec_resp.data["id"]

    existing_outcome = (
        await client.table("outcomes")
        .select("id, exit_price")
        .eq("decision_id", decision_id)
        .eq("user_id", user_id)
        .maybe_single()
        .execute()
    )

    has_existing = existing_outcome and existing_outcome.data
    is_closed = has_existing and existing_outcome.data.get("exit_price") is not None
    if is_closed:
        raise HTTPException(
            status_code=409,
            detail="Outcome already closed for this decision",
        )

    rec_resp = (
        await client.table("recommendations")
        .select("ticker, entry_price")
        .eq("id", rec_id)
        .maybe_single()
        .execute()
    )
    ticker = rec_resp.data["ticker"] if rec_resp and rec_resp.data else match["ticker"]

    commission = match.get("total_commission", 0.0)
    brokerage_fields = {
        "entry_price": match["avg_price"],
        "shares": match["total_shares"],
        "source": "questrade",
        "brokerage_order_id": match["questrade_order_id"],
        "commission": commission,
        "currency": match.get("currency", "CAD"),
        "entry_timestamp": match.get("executed_at"),
        "notes": (
            f"Auto-imported from Questrade order {match['questrade_order_id']}. "
            f"Commission: ${commission:.2f} {match.get('currency', 'CAD')}."
        ),
    }

    if has_existing:
        outcome_id = existing_outcome.data["id"]
        await client.table("outcomes").update(brokerage_fields).eq("id", outcome_id).execute()
    else:
        outcome_id = uuid.uuid4().hex
        await (
            client.table("outcomes")
            .insert(
                {
                    "id": outcome_id,
                    "user_id": user_id,
                    "decision_id": decision_id,
                    "recommendation_id": rec_id,
                    "ticker": ticker,
                    **brokerage_fields,
                }
            )
            .execute()
        )

    await (
        client.table("pending_matches")
        .update({"status": "confirmed"})
        .eq("id", body.match_id)
        .execute()
    )

    return {"outcome_id": outcome_id, "status": "confirmed"}


@router.delete("/reject-match/{match_id}")
async def reject_match(match_id: str, user_id: CurrentUser) -> dict[str, str]:
    """Reject a pending match so it won't be shown again."""
    client = await get_db()

    existing = (
        await client.table("pending_matches")
        .select("id")
        .eq("id", match_id)
        .eq("user_id", user_id)
        .eq("status", "pending")
        .maybe_single()
        .execute()
    )
    if not existing or not existing.data:
        raise HTTPException(status_code=404, detail="Pending match not found")

    await (
        client.table("pending_matches").update({"status": "rejected"}).eq("id", match_id).execute()
    )
    return {"status": "rejected"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _enrich_matches_with_recs(
    matches: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Attach recommendation details to match dicts for response building.

    Args:
        matches: List of raw pending_matches rows.

    Returns:
        Same list with ``rec_ticker``, ``rec_action``, ``rec_confidence``,
        and ``rec_entry_price`` fields added.
    """
    if not matches:
        return matches

    client = await get_db()
    rec_ids = list({m["recommendation_id"] for m in matches})
    rec_resp = (
        await client.table("recommendations")
        .select("id, ticker, action, confidence, entry_price")
        .in_("id", rec_ids)
        .execute()
    )
    rec_map = {r["id"]: r for r in (rec_resp.data or [])}

    for m in matches:
        rec = rec_map.get(m["recommendation_id"], {})
        m["rec_ticker"] = rec.get("ticker", "")
        m["rec_action"] = rec.get("action", "")
        m["rec_confidence"] = rec.get("confidence", 0.0)
        m["rec_entry_price"] = rec.get("entry_price")

    return matches


def _match_to_response(m: dict[str, Any]) -> PendingMatchResponse:
    """Convert a match dict to a PendingMatchResponse model.

    Args:
        m: Match dict (from DB or freshly created).

    Returns:
        Validated PendingMatchResponse.
    """
    return PendingMatchResponse(
        id=m["id"],
        recommendation_id=m["recommendation_id"],
        questrade_order_id=m["questrade_order_id"],
        ticker=m["ticker"],
        side=m["side"],
        avg_price=m["avg_price"],
        total_shares=m["total_shares"],
        total_commission=m.get("total_commission", 0.0),
        currency=m.get("currency", "CAD"),
        executed_at=str(m["executed_at"]),
        match_score=m.get("match_score", 0.0),
        match_reason=m.get("match_reason", ""),
        status=m.get("status", "pending"),
        rec_ticker=m.get("rec_ticker", ""),
        rec_action=m.get("rec_action", ""),
        rec_confidence=m.get("rec_confidence", 0.0),
        rec_entry_price=m.get("rec_entry_price"),
    )
